version: "3.8" 
services:
  password-protected-ui:  # connect to gcp backend
    image: test-mlflow-htpasswd  # image containing sql proxy
    
    # mount htpasswd file so it is not built into container (unsafe)
    volumes:
      - type: "bind"
        source: ${PWD}/htpasswd
        target: /etc/nginx/.htpasswd
        read_only: true

    # I'm already running something on port 5000, so I chose 5111 as an unused port
    ports:
      - target: 5000
        published: 5111
        protocol: tcp
        mode: host

    # restart nginx to use mounted htpasswd file with proxy
    entrypoint: bash -c "service nginx restart && mlflow ui" 

